# -*- coding: utf-8 -*-
"""ProvaIFB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HM9pyKRLLoJnbKFxqsbYM42TG9AwjT8M

Prova IFB:


Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link
de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em
minutos). Tempo é igual ao tamanho em MB multiplicado por 8, dividido pelo link e dividido por 60. Usar
funções.
"""

tamanhoArquivo = float(input('Digite o tamanho do arquivo para download em Mb: '))
velocidade = float(input('Digite a velocidade do seu link de internet e Mbps: '))

def tempoFinal(tamanho, vel):

    total_segundos = tamanho * 8 / vel
    total_minutos = total_segundos / 60
    return total_minutos

tempo_download_minutos = tempoFinal(tamanhoArquivo, velocidade)
print(f"O tempo aproximado de download é de {tempo_download_minutos:.2f} minutos.")